### ISSUE TITLE
ss_cnip.pac里的白名单规则是根据什么自动生成的？

### ISSUE THREAD

**Issue by allenchennnn** [HMBSbige/GetCNDomainsAndIPv4#2]
ss_cnip.pac里的：
IP白名单是根据delegated-apnic-latest文件生成的吗？
域名白名单是根据accelerated-domains.china.conf吗？

另外既然前面有IP白名单了，那域名白名单不是多余的吗？还是有什么其它的作用？

**Comment by HMBSbige** [comment]
不多余，ss_cnip.pac是先判断域名白名单，如果不在里面再判断IP。
因为有些国外网站是在墙的白名单里的，比如 store.steampowered.com。

**Comment by allenchennnn** [comment]
@HMBSbige 
ss_cnip.pac里的：
IP白名单是根据delegated-apnic-latest文件生成的吗？
域名白名单是根据accelerated-domains.china.conf吗？

我用了这个PAC后，打开huya.com却是代理连接
用chn_ip.txt 打开huya.com是本地连接
这怎么解释

**Comment by HMBSbige** [comment]
我打开是正常的...
我怀疑是你配置不对，请详细说明你的配置（根目录文件、代理规则、系统代理模式等）

**Comment by allenchennnn** [comment]
chn_ip.txt：是用delegated-apnic-latest生成的
pac.txt:就是ss_cnip.pac但我把其中的域名白名单部分删除了
用SSR的查看日志：
用PAC模式，huya.com连接的CDN是国外的
用全局模式+绕过局域网和大陆，huya.com连接的CDN是国内的

**Comment by allenchennnn** [comment]
有点晕了，我就想知道 chn_ip.txt 里的IP白名单部分的数据是不是来自delegated-apnic-latest文件

**Comment by HMBSbige** [comment]
我按照你的方法测试，测试结果居然是相反的..
理论来说也应该是这样，不知道为什么你会正好反过来..
能否把节点信息去掉后把文件夹传给我测试

**Comment by HMBSbige** [comment]
是的，chn_ip.txt是靠delegated-apnic-latest生成的

**Comment by allenchennnn** [comment]
我是这样测试的：
PAC模式：把chn_ip.txt 和 delegated-apnic-latest先移到别的文件夹
全局模式：把pac.txt文件移到别的文件夹
https://drive.google.com/open?id=128iCl2TvCCWIV89G9lk2H1hPofZjxQYe

**Comment by HMBSbige** [comment]
用了你的配置，我的测试结果还是一样...
另外，PAC模式和全局只要右键托盘图标改系统代理模式就行了，不需要移文件
没特别需求负载均衡最好关掉，PAC时代理规则最好选全局

**Comment by allenchennnn** [comment]
又搞错了，
我想问的是 ss_cnip.pac 里的IP白名单部分的数据是不是来自delegated-apnic-latest文件。

如果 ss_cnip.pac 和 chn_ip.txt的数据都是来自delegated-apnic-latest文件。
那么测试的结果 要么全走代理，要么全部直连。不可能是一个代理一个直连的。

**Comment by HMBSbige** [comment]
ss_cnip.pac 里的IP白名单部分的数据是来自 delegated-apnic-latest 文件。

就应该是一个代理一个直连。
首先， huya.com有既有外国CDN，也有国内CDN。
全局模式+代理规则绕过局域网和大陆：会用代理的DNS解析huya.com，如果你的服务器是在国外那必然解析到国外的CDN
PAC模式+代理规则全局：会先用本地DNS解析，如无效再用远程DNS解析。因为huya.com没被墙，一般不会无效，所以应该的本地DNS解析的结果。我本地DNS是国内的，所以会解析到国内DNS。

以上是理论结果，我实际使用也是一样的，不知道你哪里出了差错
![](https://user-images.githubusercontent.com/19153265/34931232-a7b00dd6-fa08-11e7-89b8-bd15d178a319.png)

**Comment by allenchennnn** [comment]
https://drive.google.com/open?id=128iCl2TvCCWIV89G9lk2H1hPofZjxQYe
请看视频，能否teamviewer远程

**Comment by allenchennnn** [comment]
https://drive.google.com/open?id=1Pcb1K89uBJ0zbEdH-s-T0iecMheiow1Z
刚才链接错了，能否teamviewer远程？

**Comment by HMBSbige** [comment]
可以teamviewer远程

**Comment by allenchennnn** [comment]
508 293 730
9045

**Comment by HMBSbige** [comment]
当选择PAC+全局的时候，ssr里提供的日志是不会显示Direct Connect的
具体原理可以仔细看看刚刚我发的图（Direct connect显示的是代理规则决定的直连，而PAC决定的直连根本就没经过SSR）。
所以到底是走了代理还是直连是要看流量的，经过多次断开连接、刷新网页、更换你的节点和观察流量，
发现有时候会直连，有时候会代理。
这...这应该是你远程DNS和CDN的锅...

我还是推荐你不要把域名白名单去了，这样就不会有那么多事情了
顺便推荐我把PAC更新地址更换的版本：
https://github.com/HMBSbige/shadowsocksr-csharp
这样你就可以一键更新PAC，我每个月都会更新PAC的...

**Comment by HMBSbige** [comment]
就是更新PAC为绕过大陆IP等替换成了我的地址

**Comment by allenchennnn** [comment]
HMBSbige/shadowsocksr-csharp 这版本的PAC访问虎牙还是会代理连接。
shadowsocksrr/shadowsocksr-csharp 这版本的没问题。

**Comment by HMBSbige** [comment]
因为那个就是老的，还是自己询问自己的节点提供商吧，我这边检查不出什么bug
