### ISSUE TITLE
能否加个精简版的 GFWList 。

### ISSUE THREAD

**Issue by allenchennnn** [HMBSbige/GetCNDomainsAndIPv4#4]
我又来了。被 DNS 污染和运营商的某些问题搞得好烦！
能否在白名单中加入这个 300 条规则的精简版 GFWList，只包含国外常用网站，不会挺慢速度啦！
https://github.com/gfwlist/tinylist。
IOS上的两款优秀的 APP : Quantumult 和 Shadowrocket ，内置黑名单+白名单+GeoIP。
还有网络上一些优秀的规则，也是采用黑名单+白名单+GeoIP。

除了 windows 上目前没有像样的名单，其它平台的都比较不错了，您是否愿意为 winddows 用户出份力。

**Comment by HMBSbige** [comment]
...
#3 你看过没，白名单都要爆了火狐的PAC buffer了，你还要再增加...拜托，现实点

除非你能增加火狐PAC模块的buffer，那我就无话可说。

当然你也可以雇我做个私人定制版的...

无污染DNS很好解决，你可以自己搭建 https://github.com/HMBSbige/DNServer (文档我还没写)

也可以用现成的
* 101.6.6.6:53
* 202.141.162.123:53
* 223.113.97.99:53
* 208.67.222.222:5353
* 208.67.220.220:443

**Comment by HMBSbige** [comment]
运营商问题就加钱换好一点的咯，不然还能怎么办

**Comment by Itzamana** [comment]
一直在用“全局模式+绕过局域网和大陆”，不知道为什么用的人很少…大家都喜欢用PAC…
