### ISSUE TITLE
生成chn_ip后报错

### ISSUE THREAD

**Issue by zyOverture** [HMBSbige/GetCNDomainsAndIPv4#5]
正在分析 CNIPv4...
Apnic:共有8356条。
IpipNet:共有5656条。
正在生成 chn_ip.txt,add.txt,del.txt...
生成成功！

正在分析 CNDomains...

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at getcnIP_dotnetcore.Program.Main() in D:\git\GetCNDomainsAndIPv4\getcnIP-dotnetcore\Program.cs:line 40

我用  dotnet 2.2.105 生成的程序  运行到Program.cs:line 40
这里的时候报了这个错，我看代码里这里已经做了判空了 为啥还有报错呢

**Comment by HMBSbige** [comment]
我这里没法复现...

**Comment by HMBSbige** [comment]
是你没有 whitelist.txt 导致的，我这边马上修复，你可以随便加个白名单域名临时解决

**Comment by zyOverture** [comment]
更新重新编译解决  3Q！
