### ISSUE TITLE
这能随机生成国内ip和域名？

### ISSUE THREAD

**Issue by ds1314** [HMBSbige/GetCNDomainsAndIPv4#6]
这能随机生成国内ip和域名？每次生成都是一样的啊

**Comment by HMBSbige** [comment]
什么随机？？？

你是小白还是来找茬的

**Comment by ds1314** [comment]
> 什么随机???
> 
> 你是小白还是来找茬的

大佬，我怎敢来找茬，只是按照项目标题，我以为实现了，随机国内ip，域名生成呢。所以问一下

**Comment by HMBSbige** [comment]
> > 什么随机???
> > 你是小白还是来找茬的
> 
> 大佬，我怎敢来找茬，只是按照项目标题，我以为实现了，随机国内ip，域名生成呢。所以问一下

这是生成全部的啊，为什么要随机啊？？？

**Comment by ds1314** [comment]
> > > 什么随机??? 
> > > 你是小白还是来找茬的
> > 
> > 
> > 大佬，我怎敢来找茬，只是按照项目标题，我以为实现了，随机国内IP，域名生成呢。所以问一下
> 
> 这是生成全部的啊，为什么要随机啊???

可能我们的想法不一样，难道域名只有6万多，我想的是，生成无数的domainurl

**Comment by HMBSbige** [comment]
这个相当于获取已知的啊
